### ISSUE TITLE
Pillows not displaying

### ISSUE THREAD

**Issue by Philip6294** [ToniMacaroni/CustomPillows#2]
Pillows aren't displayed in Default Constellation and 9 Pictures selected

Mod Menu shows this 
![20201219164709_1](https://user-images.githubusercontent.com/18615404/102693334-29097280-421a-11eb-9eb2-b8ecc9fae303.jpg)

Log Files: 
[_latest.log](https://github.com/ToniMacaroni/CustomPillows/files/5719694/_latest.log)
CustomPillows Log: 
[_latest.log](https://github.com/ToniMacaroni/CustomPillows/files/5719695/_latest.log)

Mod Version: 0.0.2
Game Version 1.13

**Comment by ToniMacaroni** [comment]
I released the 0.0.3 version which should fix it.

**Comment by Philip6294** [comment]
Jup, that fixed it thanks

**Comment by Philip6294** [comment]
So I just tried to play with Version 0.0.3 and now there aren't any maps loading, it just shows a black screen.
The Log is full with Critical messages about NullReferenceExceptions.

**Comment by ToniMacaroni** [comment]
can you redownload the version, I noticed it too and I replaced the release. Seems like you downloaded it in the short window I replaced it.

**Comment by Philip6294** [comment]
Just tried the latest Release, it works now.
